### ISSUE TITLE
Travis testing

### ISSUE THREAD

**Issue by benjaoming** [django-dbbackup/django-dbbackup#51]
This is not a classical tool to test! Ideally, we want to test it from outside. A `.travis.yml` could look something like this (sketch) :

```yml
language: python
python:
- '2.6'
- '2.7'
- '3.4'
install:
-  pip install -r requirements/development.txt
-  pip install coveralls
-  pip install django
script:
- cd testproject
- python manage.py syncdb --noinput --settings=settings.use_sqlite
- python manage.py dbbackup (...) --settings=settings.use_sqlite
- python manage.py syncdb --noinput --settings=settings.use_mysql
- python manage.py dbbackup (...) --settings=settings.use_mysql
- # Continue to do whatever changes are needed
notifications:
  irc: #django-dbbackup
after_success:
- coveralls
```

This requires the creation of `testproject` which should hold settings modules for every individual database backend that dbbackup supports.
